### PR TITLE
Create Header component

### LINKED ISSUE #7: Create a header component

### PR DESCRIPTION
**Pull request by bryanjhdang**
Make a basic header component with a title, and links on the right for `Characters`, `About`, and `Log Out`. Right now these buttons do absolutely nothing.

Fixes #7

image

### CODE REVIEW

**Comment by bryanjhdang** [comment]
Also we will probably have to re-organize our directory structure soon. It's already getting messy

**Comment by JoshuaJLi** [comment]
Going off of [this](https://legacy.reactjs.org/docs/faq-structure.html) we could do folders for `about`, `creation`, `saved sheets`, and maybe an overall `utilities` for headers and stuff

**Comment by bryanjhdang** [comment]
Yeah I agree, we can do it by route.

**Comment by bryanjhdang** [comment]
Updated so that there is now: `about`, `characters`, `creation`, `sheet`, and `utilities` directories for each route.

**Pull request merged**
